mozmeao/springfield

springfield/cms/cms_only_urls.py, springfield/cms/middleware.py, springfield/cms/tests/test_middleware.py, springfield/settings/base.py
See original description: https://github.com/mozilla/bedrock/pull/15937
=> Support failing over to a different, preferred locale for CMS pages upon 404

springfield/firefox/templates/firefox/channel/desktop.html, springfield/firefox/templates/firefox/releases/nightly-notes.html
Removes remaining X / Twitter links
http://localhost:8000/en-US/channel/desktop/
=> Remove remaining Twitter links

.github/workflows/build-and-push.yml
...to avoid getting permission denied
=> Add build environment to GAR push

requirements/dev.txt, requirements/prod.in, requirements/prod.txt, springfield/base/tests/data/example_sentry_payload.json, springfield/settings/base.py
`$POD_IP,` is prepended to the env var for `ALLOWED_HOSTS` allowing us serve readiness and health checks at the pod level.
=> Update ALLOWED_HOSTS to support pod IP

package-lock.json
Following a nudge from dependabot
=> (chore) Security: Bump babel and eslint's plugin-kit

requirements/dev.txt, requirements/prod.in, requirements/prod.txt, springfield/settings/base.py
Upgrading step-wise to Django 5.2 LTS.
=> Upgrade to Django 5.0.x

package-lock.json, package.json, tests/unit/spec/base/stub-attribution/stub-attribution.js
Replaces https://github.com/mozmeao/springfield/pull/65
=> Bump sinon from 19.0.2 to 20.0.0

.github/workflows/publish_docs.yml
Similar to [mozilla/bedrock#16182](https://github.com/mozilla/bedrock/pull/16182/files)
=> Limit publish_docs to mozmeao/springfield

springfield/cms/middleware.py, springfield/cms/tests/test_middleware.py, springfield/settings/__init__.py
Port-over of https://github.com/mozilla/bedrock/pull/16223/
=> Port over null byte fixup

springfield/settings/base.py
Correctly categorize Indian locales
https://github.com/mozilla/bedrock/issues/16253
View `/locales/` to verify the correct categorization.
=> Correctly categorize Indian locales

springfield/settings/__init__.py
=> Add allowance to CSP for loading release notes images from WMO

media/css/m24/components/navigation-refresh.scss
See: https://github.com/mozilla/bedrock/pull/16147
https://github.com/mozilla/bedrock/issues/15873
=> Fx–themed pages briefly show blue links in nav on hover

springfield/firefox/templates/firefox/releases/notes.html
See https://github.com/mozilla/bedrock/pull/16097
N/A
http://localhost:8000/en-US/firefox/138.0.1/releasenotes/
=> Update Release notes feedback and bugzilla links

media/js/base/protocol/m24-keyboard-focus-trap.es6.js, media/js/base/protocol/m24-menu.es6.js, media/js/base/protocol/m24-navigation.es6.js
See: https://github.com/mozilla/bedrock/pull/16152
https://github.com/mozilla/bedrock/issues/16090
=> Fix mobile navigation keyboard focus trap

media/css/firefox/download/basic/thanks.scss, media/css/firefox/download/desktop/thanks.scss
See: https://github.com/mozilla/bedrock/pull/16250
N/A
http://localhost:8000/en-US/download/thanks/
=> Increase visibility of help link on download thanks

media/css/protocol/protocol.scss, package-lock.json, package.json, springfield/base/templates/base-error.html
=> Protocol v21.1.0

media/css/firefox/home-en-us-ca.scss
Fixup asset location when moving from wmo page structure to fxc.
Aimed to resolve https://github.com/mozmeao/springfield/actions/runs/15173530262/job/42669077848#step:6:12745 and start building again.
=> Fix home (US/CA) build failure

tests/functional/firefox/test_home.py, tests/functional/test_navigation.py, tests/pages/base.py
This PR fixes the failed tests here: https://github.com/mozmeao/springfield/actions/runs/15190373793/job/42721363082
1. Test for homepage variation based on locale
2. Tests for new site navigation
=> update tests for new homepage variation and new site navigation

springfield/firefox/templates/firefox/features/translate.html
Removed several summers ago.
Falls back to article/base defaults.
Fixes #167
=> Unlink dead OG/social preview

tests/playwright/specs/products/firefox/firefox-default.spec.js
Following up from #159
https://github.com/mozmeao/springfield/actions/runs/15208510768/job/42777060145#step:5:445
#128
https://github.com/mozmeao/springfield/actions/runs/15209375237/job/42779721574 ✅
=> Update path in firefox-default test spec

tests/pages/firefox/browsers/desktop_landing.py
[Tests are passing.](https://github.com/mozmeao/springfield/actions/runs/15219830260)
=> Update test page location

springfield/firefox/templates/firefox/features/translate.html, springfield/firefox/views.py
Porting https://github.com/mozilla/bedrock/pull/15962
http://localhost:8000/en/features/translate/
http://localhost:8000/nl/features/translate/
=> Add ja+ko+zh to translations feature

springfield/firefox/templates/firefox/all/base.html
Cross-porting https://github.com/mozilla/bedrock/pull/16274
=> (fix) Port fix from Bedrock to stop /all being crawled

l10n/en/banners/m24-pencil-banner.ftl, springfield/base/templates/includes/banners/pencil-banner.html
This PR updates the pencil banner content in preparation for site launch.
Pencil banner on homepage.
https://github.com/mozmeao/springfield/issues/206
=> update pencil banner for launch (fix #206)

tests/playwright/specs/products/firefox/firefox-platforms.spec.js
Updates page info for fxc.
https://github.com/mozmeao/springfield/actions/runs/15717605917/job/44320423861
Closes #193
=> Fixup platform download tests

springfield/firefox/templates/firefox/browsers/mobile/includes/s2d-android.html
Update QR code UTM source (non-qr codes will be addressed in larger, separate PR)
addresses https://github.com/mozmeao/springfield/pull/266/files#r2135634265
http://localhost:8000/skr/browsers/mobile/android/
=> Update qr code utm source

springfield/firefox/templates/firefox/download/desktop/base.html
=> Update GSC verification code

.github/workflows/cdn_tests.yml, .github/workflows/download_tests.yml, springfield/firefox/redirects.py, tests/redirects/map_all_redirects.py
* Fixes CDN test failure
* Re-enables scheduled Download and CDN tests
=> Hotfix ci tests

media/css/protocol/protocol.scss
force hash update for protocol.css
=> force hash update for protocol.css

media/css/protocol/protocol.scss
This reverts commit 77b065ad015a07a1f4bdbc03e3c374f7ca34c33e.
=> Revert "force hash update for protocol.css"

springfield/firefox/firefox_details.py, springfield/firefox/tests/test_firefox_all.py, springfield/firefox/views.py
Fixes #467
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/WT-158)
=> Add ESR Linux/ARM64 builds to firefox/all

l10n/en/firefox/download/home.ftl
https://github.com/mozilla-l10n/www-firefox-l10n/pull/85#discussion_r2407513964
Updated spacing around ... on section
=> l10n request: fix spacing
