- .github/PULL_REQUEST_TEMPLATE.md
- springfield/base/templates/base-error.html
- springfield/base/templates/base-protocol.html
- springfield/cms/templates/cms/simple_rich_text_page.html
- springfield/firefox/templates/firefox/download/desktop/base.html
- springfield/firefox/templates/firefox/includes/sub-nav-firefox.html
- springfield/firefox/templates/firefox/releases/notes.html
- springfield/firefox/templates/firefox/releases/system_requirements.html
- springfield/firefox/templates/firefox/testflight.html
- Reinstates `page_title_prefix` and `page_title_prefix` (which turns out are used on a small number of pages still)
- Fixes hard coded `/features/` page link in Firefox sub navigation.
N/A
Check page titles match what's in prod for mozorg:
- http://localhost:8000/en-US/download/
- http://localhost:8000/en-US/download/?xv=basic
- http://localhost:8000/en-US/ios/testflight/
> Misc fixes

- .gitignore
- bin/db_s3_utils.py
- bin/export-db-to-sqlite.sh
- bin/run-db-download.py
- bin/run-db-upload.py
- bin/run-prod.sh
- docker/envfiles/demo.env
- docker/envfiles/master.env
- docker/envfiles/prod.env
- docker/envfiles/stage.env
- springfield/base/views.py
- springfield/settings/base.py
This changeset switches the sqlite DB from bedrock.db to springfield.db. There has also been infra work to bootstrap the S3 buckets that hold these files to download. 
In a short time, we'll switch to GCS for the file storage, but I wanted to get this working as-is for now.
* `rm data/springfield.db`
* `make preflight`
* Confirm there's a new DB file at `data/springfield.db`
* Run the site - see if releasenotes works
> Update db filename

- .github/workflows/cdn_tests.yml
- .github/workflows/download_tests.yml
- tests/functional/test_cdn.py
This is a first swing at making the CDN and Download tests pass, which are currently failing in part because they are intended for prod and we don't have prod up yet, and certainly not yet on www.firefox.com.
In the meantime, I've disabled the schedule and we should at least be able to run the tests against Dev to check that the paths they are seeking are correct, etc
> Fix CDN and download tests

- .github/workflows/send_firefox_fluent_strings_to_l10n_org.yml
- l10n/configs/pontoon.toml
...which got lost when pruning out mozorg-related Pontoon config
Resolves #73 
We should be able to see this change flow all the way from `mozmeao/springfield` to `mozilla-l10n/www-firefox-l10` and then back to `mozmeao/www-firefox-l10n`
> (chore) L10N: reinstate updated Pontoon config for newsletters.ftl

- tests/functional/conftest.py
The error:
WebDriverException: Message: Sauce-specific capabilities are no longer accepted as W3C WebDriver capabilities: avoidProxy, tags. Ensure to enclose these in sauce:options capabilities.
> Fix saucelabs errors after upgrades

- .github/workflows/build-and-push.yml
- springfield/cms/models/pages.py
- springfield/firefox/models.py
Wagtail 6.4 allows us to spec the fields to show on an editor view just by the string name of the field now, so `"myfield"` rather than `FieldPanel("myfield")`. We tried that in 469d64c but unfortunately it doesn't work for us, with `./manage.py migrate --check` (and probably other management commands) causing a blow up, blocking pre-commit locally.
```
...
File "/Users/steve/.pyenv/versions/springfield/lib/python3.12/site-packages/wagtail/admin/panels/group.py", line 74, in on_model_bound
self.children = [child.bind_to_model(self.model) for child in self.children]
^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'bind_to_model'
```
This changeset returns us to the use of `FieldPanel()` and also tweaks a misleading logging typo around container-image building
> Fix wagtail admin  re panel naming

- springfield/settings/__init__.py
* Adds support for expanding `CSP_DEFAULT_SRC` via an env var
* Switches to walrus operator to make things slightly less verbose
Resolves #89 
```
$ ./manage.py shell
>>> from django.conf import settings
>>> settings.CONTENT_SECURITY_POLICY  # should contain only defaults
>>> exit
$ export CSP_DEFAULT_SRC=test.example.com
>>> from django.conf import settings
>>> settings.CONTENT_SECURITY_POLICY  # should contain `test.example.com` as a `connect-src` value in addition to all the original ones
> 89 csp connect src expansion

- springfield/settings/__init__.py
This refactors the CSP settings a bit to consolidate patterns, layer on better security practices, and bring some of the report-only policies into the enforced policy.
I tried to break this down into logical commits as much as possible to help show the rationale, but happy to connect for a walk-through if needed. 
I did some local driving and things looked good. Anything I found locally I fixed.
E.g. the newsletter sign-up at `/en-US/developer/` was blocked due to `connect-src` not having a basket url (whereas on bedrock the `*.mozilla.org` wildcard catches that), and that is now fixed here.
> Refactor CSP settings

- Dockerfile
It seems to be needed at runtime when calling `import psycopg`
> Add libpq-dev to app-base container

- springfield/settings/__init__.py
Springfield is accessible under different URLs (origin and CDN) but `STATIC_URL` points to specific URL. We encountered CSP issues when these don't match. This patch allows the origin host to be configured and added to the CSP where appropriate to allow the assets to load.
> Add `CSP_ORIGIN_HOST_FALLBACK` to appropriate CSP settings

- springfield/firefox/templates/firefox/channel/base.html
- springfield/firefox/templates/firefox/developer/index.html
- springfield/firefox/templates/firefox/includes/sub-nav-firefox.html
Replaces outdated Firefox family logo with regular browser logo.
N/A
- http://localhost:8000/en-US/download/
- http://localhost:8000/en-US/channel/desktop/
- http://localhost:8000/en-US/developer/
> Replace Firefox family logo with browser logo

- springfield/firefox/firefox_details.py
- springfield/firefox/tests/test_firefox_all.py
- springfield/firefox/tests/test_helpers.py
See https://github.com/mozilla/bedrock/pull/16066
N/A
http://localhost:8000/en-US/download/all/
> Add Release, Beta, and Developer Edition Linux/ARM64 builds to firefox/all

- media/css/firefox/releasenotes.scss
See: https://github.com/mozilla/bedrock/pull/16251
N/A
http://localhost:8000/en-US/firefox/138.0/releasenotes/
> Add affordance to progressive rollout indicator on release notes

- bin/cron.py
- bin/run-prod.sh
* Remove need for the DB to be downloaded before startup if DATABASE_URL shows it's postgres
* Optimise speed of l10n updating by adding a new scheduled task that only does l10n files not also a DB; this avoids breaking demos and springfield-test
Resolves #49 
We're gonna need to try this on springfield-dev. I've got an infra PR here which disables the DB-download initContainer sidecar, and also uses the l10n-only scheduled job: https://github.com/mozilla-it/webservices-infra/pull/5518
We should also push main to run-integration-tests if Dev comes up fine after everything is merged
> Bootup optimisations

- springfield/settings/__init__.py
Rename env var to be more descriptive that we're just allowing assets to load from the CDN.
> Rename CSP assets host to be more descriptive

- l10n/en/download_button.ftl
- l10n/en/firefox/download/desktop.ftl
- media/css/firefox/landing/get/marketing-opt-out.scss
- media/js/base/stub-attribution/stub-attribution.js
- media/js/firefox/landing/get/marketing-opt-out-init.es6.js
- media/js/firefox/landing/get/marketing-opt-out.es6.js
- media/static-bundles.json
- springfield/firefox/templates/firefox/download/desktop/download.html
- springfield/firefox/templates/firefox/landing/get.html
- springfield/firefox/urls.py
- tests/unit/spec/base/stub-attribution/stub-attribution.js
- tests/unit/spec/firefox/landing/marketing-opt-out.js
Migrates marketing ToS opt-out landing page from bedrock.
See https://github.com/mozilla/bedrock/pull/15992 for page specific behavior  to test.
#128
http://localhost:8000/en-US/landing/get/
> Migrate firefox/landing/get to springfield (Issue #128)

- .dockerignore
To make sure generated credentials from `google-github-actions/auth` in CI are not included in any image.
- https://github.com/mozilla/bedrock/pull/16158
The OIDC token is pretty short-lived, but still might be valid longer than build+push and then pull to exfiltrate it — an alternative/addition could be `run: docker logout` in the CI to revoke the token earlier once done.
Nonetheless this is not an issue in the current setup, where images are built logged-out, then pushed to public dockerhub repo with CI secrets, and only after that pulled, tagged, and published to GAR for deployment when logged-in only using the already built images from the previous job. So this is not a concern with the current runs, more of a failsafe in case the build would run logged-in for whatever reason. …
> add GCP token file to .dockerignore

- media/css/firefox/unsupported-systems.scss
- media/static-bundles.json
- springfield/firefox/templates/firefox/unsupported-systems.html
- springfield/firefox/urls.py
From www.mozilla.org/firefox/unsupported-systems/ to /browsers/unsupported-systems
Note that this page was not localised in Bedrock, so isn't localised here.
Instead of pointing to /new/ (which doesn't exist in Springfield), I'm pointing to the root page, ahead of https://github.com/mozmeao/springfield/issues/116 landing
Part of #128
Compare http://localhost:8000/en-US/browsers/unsupported-systems/ with https://www.mozilla.org/en-US/firefox/unsupported-systems/
> (feat) Port unsupported-browsers page from Bedrock

- springfield/base/tests/test_views.py
- springfield/base/views.py
This is in addition to existing logic that will disallow all robots if the site is not being served on the production domain
Resolves #141
Unit tests passing is enough (and practical) for now
> (feat) Use a switch to disallow all robots, if we want to

- test-results/.last-run.json
- tests/playwright/specs/products/firefox/firefox-home.spec.js
Following up from #154, the locale would change the appstore links, too.
To point to a different version of the page, a different locale is used. This renders some URLs with different values.
> Update appstore test to gb URLs

- springfield/firefox/tests/test_views.py
- springfield/firefox/urls.py
URL path change for the already-ported set-as-default pages
L10N files are also already set up.
#128
* http://localhost:8000/en-US/landing/set-as-default/ links to http://localhost:8000/en-US/landing/set-as-default/thanks/
* http://localhost:8000/it/landing/set-as-default/ links to http://localhost:8000/it/landing/set-as-default/thanks/
> (feat) Move set-as-default pages to below a landing/ path

- .github/workflows/integration_tests.yml
- setup.cfg
Clean up after removed Selenium IE sanity tests.
The tests are all gone. This only cleans up the leftover markers configured to run.
> Remove unused IE sanity tests config

- springfield/base/templates/includes/navigation/navigation.html
Keeps the same locale when clicking the nav logo.
https://github.com/mozmeao/springfield/pull/146#discussion_r2102406733
> Use localized home link

- media/css/m24/components/navigation-refresh.scss
- media/img/icons/caret-sprite.svg
Add icon to indicate drop down to nav
- adds CSS to display and swap the icon 
- adds a sprite with both icons (avoids a delay displaying up icon while image is requested) 
#114 
http://localhost:8000/en-US/ and interact with the header nav.
> Add icon to indicate drop down to nav (#114)

- README.md
Created https://whatsdeployed.io/s/gKn/mozmeao/springfield to see what's what.
Used origin hostnames to avoid any potential CDN getting in the way to get the newest revision.txt deployed.
Unlike bedrock, this works here as the repo doesn't have pages of tags (yet) so let's enjoy the ride while it lasts (:)
https://github.com/mozilla/bedrock/pull/16162#issuecomment-2832632415
👓 _preview: https://github.com/janbrasna/springfield/tree/whatsdeployed#readme_
> Add whatsdeployed view for dev–stage–prod

- springfield/base/templates/includes/footer/footer.html
- springfield/base/templates/includes/navigation/menus/resources.html
The content in each site will be the same, so may as well keep people on www.firefox.com
Resolves #172 - as reported by @janbrasna 
Check the nav and footer on any page
> (fix) Amend Release Notes links in Nav and Footer to point to Springfield, not www.mozilla.org

- l10n/en/footer-firefox.ftl
- media/css/protocol/components/_footer.scss
Adds missing FTL string and removes globe icon to avoid positioning issues when form height expands with addition of "Go" button
https://github.com/mozmeao/springfield/issues/225
Disable JS and go to footer on http://localhost:8000/en-US/
> Fix ftl string and remove globe on no-js lang switcher (fixes #225)

- l10n/en/brands.ftl
- l10n/en/firefox/features/private-browsing-2023.ftl
- springfield/firefox/templates/firefox/features/private-browsing.html
- springfield/firefox/templates/firefox/includes/desktop-platform-sub-nav.html
- springfield/firefox/templates/firefox/includes/sub-nav-firefox.html
- springfield/firefox/templates/firefox/more/best-browser.html
- springfield/firefox/templates/firefox/releases/notes.html
Final check on internal links now that we've ported all pages for MVP
https://github.com/mozmeao/springfield/issues/228
Check the updated links on the following pages
Check Netscape, Opera, and Safari brands are translated
> Sweep links (fixes #228)

- .github/ISSUE_TEMPLATE/bug_report.md
Seems the template minds the case difference in the issue label referenced.
Or, the other way around, fixing this by changing the actual issue label itself to Title-case to match bedrock for consistency, in which case this PR is moot.
Many! ;)
> Update bug_report template label

- media/js/base/consent/allow-list.es6.js
- tests/unit/spec/base/consent/consent-utils.js
Expand the set of pages that show cookie consent to be all of the `/landing/` pages, which are product-marketing pages.
Question - should `/landing/set-as-default/thanks/` definitely also show it? I am assuming so
*Please* shout if there are better JS tests to expand related to this changeset
Resolves #237
Ensure you have GPC / DNT disabled in your browser privacy settings.
> Expand list of pages which show the cookie consent banner

- springfield/cms/middleware.py
- springfield/cms/tests/test_middleware.py
Prior to this fix, we were looking at all (live and draft) pages to find an alternative to redirect to, which caused a 302 loop
Cross-port of https://github.com/mozilla/bedrock/pull/16205
Unit tests passing is enough
> (fix) Stop creating a redirect loop when a draft page matches a URL path - it should correctly 404

- springfield/base/templatetags/helpers.py
- springfield/base/tests/test_helpers.py
Resolves #268 where we see this bug on the /features/ pages
Locally, try some URLs and confirm they show a valid lang picker and that any lang selected is valid (and does not redirect to en-US)
http://localhost:8000/features/
http://localhost:8000/features/fast/
http://localhost:8000/de/features/
http://localhost:8000/de/features/fast/
http://localhost:8000/dsb/features/
http://localhost:8000/dsb/features/fast/
http://localhost:8000/hsb/features/
http://localhost:8000/hsb/features/fast/
http://localhost:8000/rm/features/
http://localhost:8000/rm/features/fast/
> (fix) Handle edge case in locale-list building when prefer_cms is used but there is nothing yet in the CMS

- media/css/protocol/components/_download-button.scss
- media/img/icons/m24-small/download-white.svg
- springfield/firefox/templates/firefox/all/download.html
- springfield/firefox/templates/firefox/enterprise/index.html
- springfield/firefox/templates/firefox/includes/download-button-thanks.html
- springfield/firefox/templates/firefox/includes/download-button.html
- springfield/firefox/templates/firefox/includes/macros.html
Adds download icon to all download buttons
Did I miss any other inline SVG use? Did I miss other hardcoded buttons?
https://github.com/mozmeao/springfield/issues/205
Added after review
> Add download icon to download button (fixes #205)

- springfield/firefox/templates/firefox/all/mobile.html
Resolves #242 
Also needs to be backported to Bedrock
> (fix) Ensure Send To Device email link is only shown for locales where the form is enabled

- springfield/releasenotes/models.py
- springfield/releasenotes/tests/test_models.py
Port of https://github.com/mozilla/bedrock/pull/16328/
This is because we now have more than one ESR available at any one time and the current logic doesn't expect that so just finds the youngest ESR record.
We use the product_details lib as the source of truth for which version we want for the "esr" channel, because we can't depend on the ESR versions being saved/created in a reliable order.
Manually testable by clicking the 'Release notes' link on http://localhost:8000/en-US/download/all/desktop-esr/
> Fix link to appropriate version of ESR releasenotes

- springfield/firefox/templates/firefox/features/translate.html
- springfield/firefox/views.py
Ports https://github.com/mozilla/bedrock/issues/16341 from Bedrock
> (feat) Add Arabic to list of locales supported by Firefox's Translate feature

- l10n/en/firefox/download/desktop.ftl
- media/css/firefox/download/basic/download.scss
- media/css/firefox/download/desktop/download.scss
- media/css/firefox/home-en-us-ca.scss
- springfield/firefox/templates/firefox/download/basic/base_download.html
- springfield/firefox/templates/firefox/download/desktop/download-en-us-ca.html
- springfield/firefox/templates/firefox/download/desktop/download.html
Turns home h1 into plaintext, removes mobile h2 (there are better h2s right after it) and removes decoration from basic experience.
These are the ~6 occurrences, most of which benefit from the shorter hero, however for mobile aside this makes the contained screenshot smaller, so make sure that's ok.
(I haven't removed the one on mobile product pages as that one needs to alternate between Firefox and Focus wordmarks so it's kept for consistency. If there were "Firefox for Android" or "Firefox for iOS" actual wordmarks, these would be a better fit there, to make it immediately obvious it's a mobile product…)
#180
http://localhost:8000/en-GB/
http://localhost:8000/en-US/landing/get/
http://localhost:8000/he/landing/get/
http://localhost:8000/skr/ …
> Eliminate repetitive wordmarks

- l10n/en/banners/m24-pencil-banner.ftl
- springfield/base/templates/includes/banners/pencil-banner.html
This PR removes the firefox.com link from the pencil banner.
Home page pencil banner.
https://github.com/mozmeao/springfield/issues/296
> remove pencil banner site link (fix #296)

- media/css/m24/components/navigation-refresh.scss
- springfield/base/templates/includes/navigation/nav-cta.html
- springfield/firefox/templates/firefox/download/basic/base.html
- springfield/firefox/templates/firefox/download/desktop/base.html
- springfield/privacy/templates/privacy/cookie-settings.html
Remove download button from download page
- Removes download button from download pages that appear at / 
- Adds spacer to help center navigation items when CTA is not present
Fix #311 
Fix #239 
http://localhost:8000/fr/
http://localhost:8000/fr/?xv=basic
http://localhost:8000/en-US/browsers/desktop/windows/
http://localhost:8000/en-US/privacy/websites/cookie-settings/
> Remove download button from some pages, add spacer (Fix #311)

- tests/playwright/specs/404.spec.js
- tests/playwright/specs/footer.spec.js
- tests/playwright/specs/navigation.spec.js
Allow cases where e.g. extra `utm_campaign` param is being added to the location.
```
specs/footer.spec.js:25:9 › /en-US/ footer (mobile) › Footer language change @firefox 
=========================== logs ===========================
waiting for navigation to "**/de/?automation=true" until "commit"
navigated to "https://stage.springfield.nonprod.webservices.mozgcp.net/de/?automation=true&utm_campaign=SET_DEFAULT_BROWSER"
```
Right now we don't exactly care how the query string looks like — and since the home is also download page now, it can have a varying degree or parameters added and removed etc.
Ideally it should not happen with `?automation=true` but this is a hotfix for now.
(This exact failure is weird given it comes from a Linux UA that should not be triggering said campaign, but …
> Fix homepage navigation tests with wildcards and un-wildcard some others

- springfield/firefox/templates/firefox/download/desktop/download-en-us-ca.html
Moving the id on the actual element to land on.
No matter where in DOM the banners are repositioned, this keeps their target reasonable in the document outline.
Fixes #184
http://localhost:8000/en-CA/ with UA triggering mobile aside
(or http://localhost:8000/en-CA/#next in general)
> Fix home mobile #next anchor for refresh locales

- media/js/base/banners/m24-pencil-banner.es6.js
Only init pencil banner that is actually interactive.
This skips pushing the GA datalayer in case the banner is used only as a form of notification when can't be dismissed etc. — sounds OK to me.
Fixes #328 (and possibly #324 too)
http://localhost:8000/en
http://localhost:8000/skr
http://localhost:8000/eo
> Only bind pencil-banner setup if it has close button

- media/js/base/banners/m24-pencil-banner.es6.js
Rewrites #329 in a more conservative way to avoid _SyntaxError_ on legacy IE.
Not that the button would work in IE to start with. It just seems to choke badly on a selector it doesn't understand in the JS query… TIL
#324
[/actions/runs/15898256192/job/44834926423](https://github.com/mozmeao/springfield/actions/runs/15898256192/job/44834926423) :shipit: 🚢 ✅
> Refactor pencil banner button bind for legacy IE

- springfield/firefox/templates/firefox/download/desktop/download.html
Fix case in German MR106 feature as reported via QA form. 
That’s because das ist kein Substantiv!
> Fix grammar of de hardcoded string

- .github/workflows/cdn_tests.yml
- tests/functional/test_cdn.py
If there’s no results from upstream API, these are expected to fail. Let’s mark them as such in that case, so they don’t fail the whole pipeline which is still very useful. 
Also triggers in a different time slot than bedrock so we’re not getting unnecessarily rate-limited etc.
https://github.com/mozilla/bedrock/issues/16339
> Mark missing SSL test results as `xfail`

- springfield/firefox/redirects.py
There's a few 404s so this accepts `/PAIR` as `/pair`, too.
We handle firefox.com/pair but it's expected to be typed manually — thus folks may scream and end up 404ing on FIREFOX.COM/PAIR so we should make this redirect case insensitive.
https://github.com/mozmeao/springfield/issues/336#issuecomment-3016105989
localhost:8000/PAIR
> Make FxA `/pair` vanity redirect case–insensitive

- media/css/firefox/releasenotes.scss
This fixes oversized headings in the footer which were caused by release page CSS rules that were lacking specificity.
Made the release page CSS more specific by adding the `.c-release-notes` class selector to the release notes heading styles.
This is part of Footer mobile vertical alignment #308 which may be split into a separate issue.
> Fix release notes style specificity

- springfield/base/templates/404-locale.html
- springfield/base/templates/base/locales.html
Removing WMO references, taglines and meta from locale pages.
Wording repurposed from other places.
The change on L60 key from native to English is intentional (for consistency)
Title truncated on L13 as it gets the same in suffix just below.
#292
http://localhost:8000/en-US/404-locale/
http://localhost:8000/locales/
http://localhost:8000/ (in prod mode, and with Accept-Language empty)
> Fix site details on global root and locale page

- springfield/firefox/templates/firefox/releases/notes.html
Porting over https://github.com/mozilla/bedrock/pull/16286 in case MDN starts using these…
Checked for any preexisting IDs hypothetically clashing with the note tag names used for this, but all looks good.
https://github.com/mozilla/bedrock/issues/16277
https://github.com/mozilla/nucleus/issues/1077
http://localhost:8000/firefox/128.0/releasenotes/#community
http://localhost:8000/firefox/android/128.0/releasenotes/#fixed
http://localhost:8000/firefox/ios/139.0/releasenotes/#new
http://localhost:8000/firefox/128.0beta/releasenotes/#developer
http://localhost:8000/firefox/139.0a1/releasenotes/#html5
http://localhost:8000/firefox/39.0/releasenotes/#changed
http://localhost:8000/firefox/organizations/notes/#developer
http://localhost:8000/firefox/notes/#fixed
> Add heading anchors to release notes

- media/css/firefox/more/best-browser.scss
- media/static-bundles.json
- springfield/firefox/templates/firefox/more/best-browser.html
- springfield/firefox/templates/firefox/more/cta.html
This PR fixes the style of the `best-browser` page hero and bottom CTA sections.
- hero section
- bottom CTA section
https://github.com/mozmeao/springfield/issues/350
http://localhost:8000/en-US/more/best-browser/
> fix best-browser page hero and cta section styles (fix#350)

- media/css/m24/components/navigation-refresh.scss
- springfield/base/templates/includes/navigation/nav-cta.html
This PR fixes the issue that nav content shift when download button is not displayed.
Compare navigation content when download button is displayed or not
https://github.com/mozmeao/springfield/issues/365
http://localhost:8000/en-US/browsers/mobile/
> fix nav content horizontal shift (fix #365)

- media/css/firefox/home.scss
Decrease feature heading font-size for non-EN langs
- Decreased font size for all languages on `lg` screens
- Increased font size to original value on `xl` screens for English only.
#381  (not totally fixed)
(run `make preflight` to update your local translations)
http://localhost:8000/pl/
If that doesn't work just copy/paste the long word from prod ;)
> Decrease feature heading font-size for non-EN langs (#381)

- l10n/en/banners/consent-banner.ftl
- springfield/base/templates/includes/banners/consent-banner.html
- springfield/firefox/templates/firefox/features/adblocker-2025.html
We want to make clear the consent banner applies to `firefox.com` and not `mozilla.org`
from Slack
> Update consent banner name

- media/js/base/datalayer-productdownload.es6.js
- springfield/firefox/templates/firefox/all/mobile.html
- springfield/firefox/templates/firefox/browsers/mobile/includes/s2d-ios.html
- springfield/firefox/templatetags/misc.py
- springfield/firefox/tests/test_helper_misc.py
- springfield/redirects/util.py
- tests/unit/spec/base/datalayer-productdownload.js
- This is a fix for https://github.com/mozilla/bedrock/issues/14079
- Updated the app_store_url function to include a mapping for product names to tracking codes.
- Modified the mobile_app_redirector to append tracking parameters to the app store URLs.
- Adjusted the datalayer-productdownload logic to utilize the new tracking parameters.
- Updated tests to reflect changes in URL structure and ensure correct tracking for various products.
Simplify product download tracking by replacing hardcoded app IDs with query string parameters (mz_pr) for iOS and Microsoft Store URLs (keeping existing Android Play Store tracking logic).
- Updated logic in datalayer-productdownload.es6.js to use `mz_pr` parameter for App Store and Microsoft Store URLs, inferring platform from domain (`ios` for App …
> Refactor app store URL generation and tracking parameters

- media/css/protocol/components/_footer.scss
- springfield/base/templates/includes/footer/footer.html
Changes the classnames on the "Latest Builds" and "Firefox for Business" h3 tags to `.mzp-c-footer-heading` from `.c-footer-subheading` for consistent alignment with other headings in the footer, at all breakpoints.
The vertical alignment is now fixed for breakpoints below 480px, and the h2/h3 heading levels are unchanged, but the correct semantics of the markup of this footer section still need review.
Fixes #308
> Update footer subheading classes to fix mobile vertical alignment

- media/css/firefox/download/desktop/download.scss
- media/css/firefox/home.scss
- media/js/base/fxa-form.es6.js
- media/js/base/fxa-link.es6.js
- media/js/base/mozilla-client.js
- media/js/firefox/download/desktop/download.js
- media/js/firefox/home.js
- tests/unit/spec/base/fxa-form.js
- tests/unit/spec/base/fxa-link.js
UITour doesn't work on www.firefox.com for Firefox versions before 136, stop trying.
- updated version number which indicates UITour is available
- half hearted attempt to update the comments too
Inspired by #337 may fix https://github.com/mozmeao/springfield/issues/323
You will need to be in a version of Firefox older than 136. [ESR is available here](https://www.firefox.com/en-US/download/all/desktop-esr/). 
"See your protection report" on the home page should only appear in more recent versions.
> Don't attempt UITour for Fx < 136, it's not enabled on fxc (#337)

- media/css/firefox/home.scss
This PR fixes the homepage release section style bugs.
- rtl image horizontal alignment
- mobile image alignment
https://github.com/mozmeao/springfield/issues/389
http://localhost:8000/ar/
> fix homepage release section rtl and mobile styles (fix #389)

- springfield/firefox/templates/firefox/features/translate.html
- springfield/firefox/views.py
Removed JS from base template started failing Fx vs. non-Fx CTA tests in integration, adding `super()` to load it back. Also a formatting fix for linting failing before unit tests.
Moving the JS block after the markup is loaded while at it, as is the norm around here not to block content, should not have impact on the CLDR experience as that's triggered on DOM ready now — however should in general guarantee the DOM elements would be available at that point (probably enabling further simplification of the JS to not wait for readystates at all).
Ruff formatting wrinkle fails all subsequent CI runs now after being merged on main. That line is probably about to be changed/simplified anyway so I just had ruff reformat it to its liking. …
> Fixup failing tests for features/translate changeset

- .github/workflows/routine_l10n_obsolete.yml
Open obsolete ftl reminders on different schedule to wmo (and refer the correct l10n repo).
Bedrock is run on odd months, so this aims to spread the workload/pings a bit.
[/actions/runs/16262675495/job/45911310377#step:2:50](https://github.com/mozmeao/springfield/actions/runs/16262675495/job/45911310377#step:2:50)
> Run l10n cleanup cron in even months

- media/js/base/protocol/navigation.es6.js
Changed string literal comparison to typeof check to correctly determine if window.MzpSupports object is defined.
Fix #380
> Fix typeof check for MzpSupports object in navigation Fix #380

- l10n/en/navigation-firefox.ftl
- media/css/m24/components/navigation-refresh.scss
- media/img/icons/caret-sprite.svg
- springfield/base/templates/403_csrf.html
- springfield/base/templates/includes/navigation/menus/features.html
- springfield/base/templates/includes/navigation/menus/resources.html
- springfield/base/templates/includes/navigation/navigation.html
Add menu items for "Features" navigation item.
Some headings and colors were updated with that design.
New treatment was designed for mobile panels.
Q: mobile design calls for grey inset background (only for "Features" or any nav panel?) — not being sure now how to distinguish top nav heading link vs. panel heading without a link both looking the same currently in the mobile nav, I applied the grey background to both panels to make the two heading levels more distinct.
(Fixed some whitespace in surrounding files with it.)
Changed the chevron from sprite to single icon & rotate -180deg on hover.
#235
> Add "Features" menu dropdown

- tests/playwright/specs/products/firefox/firefox-features.spec.js
Makes finding a test fail culprit easier by getting rid of false positives.
Moves the loop outside of describing the test, to make that actually distinct tests.
Fixes #412
_(Before:)_
> <img width="1130" height="734" alt="Screenshot 2025-08-11 at 12 36 33" src="https://github.com/user-attachments/assets/2546c6ca-26f3-4a0a-befa-433867494704" />
_(After:)_
> <img width="1130" height="730" alt="Screenshot 2025-08-11 at 12 40 50" src="https://github.com/user-attachments/assets/2a8637f1-52b6-40c6-bbea-0c08767e768b" />
> Fix result contamination in Playwright when looping pages

- media/css/firefox/landing/index.scss
> "The file 'img/firefox/new/desktop/android.png' could not be found"
(et al.)
Maybe we should look into having the strict builds in CI somehow before merging to verify such things. (I've def been bitten by that a few times already.)
```
3.171     cache_name = self.clean_name(self.hashed_name(name))
3.171                                  ~~~~~~~~~~~~~~~~^^^^^^
3.171   File "/venv/lib/python3.13/site-packages/django/contrib/staticfiles/storage.py", line 144, in hashed_name
3.171     raise ValueError(
3.171         "The file '%s' could not be found with %r." % (filename, self)
3.171     )
3.171 ValueError: The file 'img/firefox/new/desktop/android.png' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at …>.
------
failed to solve: process …
```
> Fixup fx/landing asset paths

- springfield/firefox/templates/firefox/landing/ios-summarizer.html
- springfield/firefox/templatetags/misc.py
- springfield/firefox/tests/test_helper_misc.py
This PR updates the `ios_url` used to redirect to app store to target the specific campaign for shake to summarize. It does this by adding a new `ppid` param. It should redirect to this instead: https://apps.apple.com/us/app/firefox-private-web-browser/id989804926?ppid=908b3bb9-aa78-4a60-8f7f-2407cd3227bc
https://github.com/mozmeao/springfield/issues/478
> Adding product page id (ppid) support

- springfield/firefox/templates/firefox/includes/download-unsupported.html
- springfield/firefox/templates/firefox/includes/macros.html
Adds special casing of `ja-JP-mac` codepage for desktop downloads via unsupported systems CTA helper/macro.
Other static CTAs should be covered already. (This aligns some naming/casing across the individual changesets too for consistency.)
Fixes https://github.com/mozmeao/springfield/issues/468#issuecomment-3276215518
#472
UA: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Safari/537.36`
http://localhost:8000/ja/
http://localhost:8000/ja/browsers/desktop/
http://localhost:8000/skr/browsers/desktop/ (control, en-US download)
http://localhost:8000/scn/browsers/desktop/ (control)
This is the "unsupported" macro:
> <img width="1352" height="296" alt="Screenshot 2025-09-17 at 20 52 36" src="https://github.com/user-attachments/assets/4cccd24b-93ab-470e-8d …
> Fix ja-JP-mac ESR115 download in unsupported macro

- tests/functional/conftest.py
Only collects link elements from within the final step of /download/all for l10n bouncer links tests.
The issue mentions several mitigations or fixes that are each valid in itself; but for this test I'd expect the constraint to be the actual content block for the final download is the expected behavior.
"5439 selected" matches the value from earlier this week when it passed correctly.
Fixes #495
```
collected 6741 items / 1302 deselected / 5439 selected
succeeded 12 minutes ago in 23m 48s
```
[`@janbrasna/springfield`/actions/runs/17884110774/job/50855539100#step:3:498](https://github.com/janbrasna/springfield/actions/runs/17884110774/job/50855539100#step:3:498) ✅ 
_(triggered from workspace changes via:)_
https://github.com/mozmeao/springfield/blob/ec1c2072ca0e03d471e23ed884a0199fe90fd8f3 …
> Fix download tests by restricting the selector only to page section content

- l10n/en/navigation-firefox.ftl
- springfield/base/templates/includes/navigation/menus/resources.html
- springfield/firefox/urls.py
Adding the new Firefox protections page to navigation
https://mozilla-hub.atlassian.net/browse/WT-266
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/WT-268)
┆Priority: P2
┆Sprint: Backlog
> Adding Firefox Protections page to navigation

- tests/playwright/specs/newsletter/newsletter-embed.spec.js
Follow up to https://github.com/mozilla/bedrock/pull/16599 where we were inadvertently testing redirected pages. This PR moves that check directly to Springfield and adds new URLs with newsletters
All newsletter pages on FXC should have associated URL in playwright tests
https://github.com/mozmeao/springfield/issues/502
https://mozmeao.github.io/platform-docs/testing/?h=play#running-playwright-tests
`npx playwright test newsletter-embed`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/WT-221)
┆Priority: P2
┆Sprint: Backlog
> Add newsletter tests for ported pages
